# Generated by Django 4.1.1 on 2022-09-28 18:26

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColourSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primary', colorfield.fields.ColorField(default='#DFD9D6', image_field=None, max_length=18, samples=None)),
                ('color_accent', colorfield.fields.ColorField(default='#DBC2D1', image_field=None, max_length=18, samples=None)),
                ('color_background', colorfield.fields.ColorField(default='#0A0A0A', image_field=None, max_length=18, samples=None)),
                ('mask_opacity', models.FloatField(default=0.5, max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
