# Generated by Django 4.1.3 on 2022-11-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloursettings',
            name='mask_opacity',
            field=models.FloatField(default=0.7, max_length=1),
        ),
    ]
