# Generated by Django 4.1.3 on 2022-12-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(default='https://freedom-dive-assets.nyc3.digitaloceanspaces.com/pfp.png'),
        ),
    ]
