# Generated by Django 4.1.3 on 2022-12-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/avatar/default.png', upload_to='avatar'),
        ),
    ]
