# Generated by Django 4.1.3 on 2022-12-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_s3_url',
            field=models.URLField(default='https://freedom-dive-assets.nyc3.digitaloceanspaces.com/avatar/pfp.png'),
        ),
    ]
