# Generated by Django 4.1.3 on 2023-01-11 18:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloursettings',
            name='color_accent',
            field=colorfield.fields.ColorField(default='#F9F7B4', image_field=None, max_length=18, samples=None),
        ),
    ]
