# Generated by Django 4.1.3 on 2023-01-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_osuoauthtoken_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osuoauthtoken',
            name='access_token',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='osuoauthtoken',
            name='refresh_token',
            field=models.CharField(max_length=3000),
        ),
    ]
