# Generated by Django 4.1.3 on 2023-02-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_osuoauthtoken_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_s3_url',
            field=models.URLField(default='https://freedomdive-assets.beatsets.info/avatar/pfp.png'),
        ),
    ]
