# Generated by Django 4.1.3 on 2023-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_avatar_s3_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_s3_url',
            field=models.URLField(default='https://freedom-dive-assets.nyc3.digitaloceanspaces.com/avatar/pfp.png'),
        ),
    ]
