# Generated by Django 4.1.3 on 2023-02-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_avatar_s3_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='background/default.png', upload_to='profile_background'),
        ),
        migrations.AddField(
            model_name='profile',
            name='background_s3_url',
            field=models.URLField(default='https://freedomdive-assets.beatsets.info/background/default.png'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_s3_url',
            field=models.URLField(default='https://freedomdive-assets.beatsets.info/avatar/pfp.png'),
        ),
    ]
