# Generated by Django 4.1.3 on 2023-02-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_background_profile_background_s3_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='background/default.jpg', upload_to='profile_background'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_s3_url',
            field=models.URLField(default='https://freedomdive-assets.beatsets.info/background/default.jpg'),
        ),
    ]
