# Generated by Django 4.1.3 on 2022-11-15 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('beatmap_id', models.IntegerField()),
                ('ruleset_id', models.IntegerField()),
                ('data', models.JSONField()),
                ('has_replay', models.BooleanField(default=False)),
                ('preserve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
