# Generated by Django 4.1.3 on 2022-11-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatmapset',
            name='difficulty_names',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
