# Generated by Django 4.1.3 on 2022-12-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0003_alter_beatmapset_difficulty_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedBeatmapInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatmap_id', models.IntegerField()),
                ('ruleset_id', models.IntegerField()),
                ('statistics', models.JSONField()),
            ],
        ),
    ]
