# Generated by Django 4.1.3 on 2023-01-20 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0004_convertedbeatmapinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('score_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('performance', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceByGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('score_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('performance', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_id', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('beatmap_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('ruleset_short_name', models.CharField(max_length=100)),
                ('passed', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
