# Generated by Django 4.1.3 on 2023-01-20 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0005_country_countrystatistics'),
        ('mirror', '0005_performance_performancebygraph_scorestore'),
    ]

    operations = [
    ]
