# Generated by Django 4.1.3 on 2023-01-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0006_merge_20230120_0447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
