# Generated by Django 4.1.3 on 2023-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0007_delete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorestore',
            name='client_md5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scorestore',
            name='client_platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scorestore',
            name='client_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
