# Generated by Django 4.1.3 on 2022-12-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0002_beatmapconvertedstatisticsimportapiusagelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beatmapconvertedstatisticsimportapiusagelog',
            old_name='beatmapset_id',
            new_name='beatmap_id',
        ),
    ]
