# Generated by Django 4.1.3 on 2023-01-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_api', '0003_rename_beatmapset_id_beatmapconvertedstatisticsimportapiusagelog_beatmap_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatmapsetLookupAPIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('beatmapset_id', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
