# Generated by Django 4.1.3 on 2022-11-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBeatmapsetUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('beatmapset_id', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
