# Generated by Django 4.1.3 on 2022-11-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('beatmap_id', models.IntegerField()),
                ('ruleset_short_name', models.CharField(max_length=100)),
                ('passed', models.BooleanField(default=False)),
            ],
        ),
    ]
