# Generated by Django 4.1.3 on 2022-11-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorestore',
            name='statistics',
            field=models.JSONField(default=dict),
        ),
    ]
