# Generated by Django 4.1.3 on 2022-12-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_clientchangelog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchangelog',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
