# Generated by Django 4.1.3 on 2022-12-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_clientchangelog_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchangelog',
            name='download_url_linux',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clientchangelog',
            name='download_url_macos',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clientchangelog',
            name='download_url_windows',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
