# Generated by Django 4.1.3 on 2023-01-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_webchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('score_id', models.CharField(max_length=100)),
                ('performance', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='scorestore',
            name='score_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
