# Generated by Django 4.1.3 on 2023-01-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_performancestore_scorestore_score_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceByGraphStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('score_id', models.CharField(max_length=100)),
                ('performance', models.JSONField(default=dict)),
            ],
        ),
    ]
